package com.soap.Temperature;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2025-08-19T12:56:45.036+05:30
 * Generated source version: 3.6.4
 *
 */
@WebService(targetNamespace = "https://www.w3schools.com/xml/", name = "TempConvertHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TempConvertHttpPost {

    @WebMethod(operationName = "CelsiusToFahrenheit")
    @WebResult(name = "string", targetNamespace = "https://www.w3schools.com/xml/", partName = "Body")
    public java.lang.String celsiusToFahrenheit(

        @WebParam(partName = "Celsius", name = "Celsius", targetNamespace = "https://www.w3schools.com/xml/")
        java.lang.String celsius
    );

    @WebMethod(operationName = "FahrenheitToCelsius")
    @WebResult(name = "string", targetNamespace = "https://www.w3schools.com/xml/", partName = "Body")
    public java.lang.String fahrenheitToCelsius(

        @WebParam(partName = "Fahrenheit", name = "Fahrenheit", targetNamespace = "https://www.w3schools.com/xml/")
        java.lang.String fahrenheit
    );
}
